name: MACOS_DEBUG => Stress Test (clang)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  run:
    runs-on: macos-13
    env:
      HOMEBREW_PREFIX: /usr/local
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Install deps
      run: |
        brew update || true
        brew install lld || true
        brew install llvm || true
        brew install clang-build-analyzer || true
        brew install --cask clay || true
        brew install boost || true
        echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

    - name: Build scarlet
      run: |
        arch -x86_64 /bin/zsh -c 'mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" .. && make -j4'
    
    - name: Test scarlet
      run: |
        arch -x86_64 /bin/zsh -c 'cd stress && ./stress_test.sh clang'
