name: UBUNTU_DEBUG => Stress Test (gcc)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: 3.25.2
    
    - name: Install deps
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo apt install gcc g++ libboost-all-dev
        
    - name: Build scarlet
      run: |
        mkdir -p build && cd build && cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug .. && make

    - name: Test scarlet
      run: |
        cd stress && ./stress_test.sh gcc
